#+STARTUP: showall
#+STARTUP: lognotestate
#+TAGS:
#+SEQ_TODO: TODO STARTED DONE DEFERRED CANCELLED | WAITING DELEGATED APPT
#+DRAWERS: HIDDEN STATE
#+TITLE: Guide to Restaurants
#+CATEGORY: todo

* Guide to Restaurants for Visitors

Victoria has a very large number of food establishments (restaurants, bars, coffee-shops). As expected, quality varies tremendously. Fortunately price does
not. For peoeple who come from Europe, Japan or expensive American cities, Victoria will feel cheap.

Of course locals have a different view of restaurants than visitors. As Anthony Bourdain says "Do not eat the hotel food" and instead try what the locals eat.

Any list has a bias. Mine is that I prefer lunch food over dinner food. I go out for lunch approximately 10 to 20 times more than dinner time. So keep that in
mind. And of course all below is simply my opinion.

My ranking:

- Fav. I really like it and I go there any chance I have
- Reg. I am a regular (I would go there at least once a month --for lunch)
- Ok. I will eat there if the need comes but I don't think about going there on my own

Prices excluding drinks (roughly) 

- Cheap: Usually below 15 dollars including tax and tip
- Mediaum: Between 15 and 20 dollars including tip 
- Expensive: More than 20 dollars

Unless indicated otherwise, I would eat in any of these places.  They are in no particular order

** Protocol

- Water is free in Canada and expected. Even fast food places and coffee shops will not hesitate to give you water if you ask for it. Restaurants will start their service with a glass of water. The water in Victoria has a good taste.
- Tipping. The standard tip in Canada is 15%. The bill at the end of your dinner will not include it unless you are a large group (in that case, ask for clarification)
- Most restaurants will take credit and debit cards (one exception is Hernande'z)
- Most restaurants will take reservations for dinner (one exception is the Brasserie L'Ecole)

** On ingredients

The world is global but there are some local staples:

- Salmon
- Halibut
- Dungeness Crab
- Albacore tuna
- Venison (deer)

** Restaurants

*** For tourists

These are good for tourists because of location, and the food is decent.

- Red fish, blue fish. Ok. This place is loved by visitors and locals. It is right on the water. Its best feature is that you eat right along the ocean.  Cheap.

- Fisherman's wharf. Ok. It has two restaurants. Mexican (Puerto Vallarta Amigos)  and and Fish and Chips (Barb's Fish and Chips). Cheap.

- Aura. http://www.aurarestaurant.ca/ Ok. This is one of my preferred restaurants when I want to feel like a tourist. The food does not impress me but the view
  is worth it. Sit in the patio, but wear warm clothes in the evening. It will get cold, even in the summer. Medium at lunch time, expensive at dinner time.

- The Marina. http://www.marinarestaurant.com/. Ok. Same as Aura, but you need a car or the bus to get there. It has the best view in Victoria, in my
  opinion. Medium at lunch time, expensive at dinner time. They have a $33+tax+tip gluttonous [[http://www.marinarestaurant.com/menus/sunday-brunch/][brunch]] on Sundays that is well regarded (but a bit pricey).

- Rebar. http://rebarmodernfood.com/ ok. This is a place that says "west coast" the most. I liked it but got tired of it over the years (the menus remained the same). It is a popular
  destination and I think their food is ok. Medium.

- Legislative Dining Room. Feel like an MP for a couple of hours. It is a secretive place, the food is ok, but the experience is what matters. It will show you
  that, at least in BC, our leaders and the people sit next to each other to enjoy a meal. Medium

*** For foodies

**** Dinner time

For me, these are the best four dinner restaurants in Victoria.

- Brasserie L'ecole. Fav. French. I love this place. One of the best of Victoria. No reservations, so you have to line up and be patient. It opens at 5:30 so arrive at
  5:15 or around 7:00 PM (come in, make your request, and go wander around; they will text you when your table is available). Great value for the money.  Expensive

- Camille's. Fav. French with westcoast and modernist influence. Another one of my favorities, but one of the most expensive in town. Great, great food, but
  feels a bit more formal. They don't serve lunch any more :( Expensive

- Ulla. Reg. Modernist. Less expensive than Mattise but more than the Brasserie.  Expensive.

- Cafe Brio. French with westcoast influence. I go there once in a while and I am always relatively happy with the food, but i would prefer any of the other three above
  first. I have been told their wine list is good. Expensive.

**** Dinner or Lunch

- Zambri's. Napolitan style pizza Ok. This used to be one of my favorite restaurants but it is a bit inconsistent now (at lunch time, I rarely go there for
  dinner). Their pizza is probably the best downtown. They have specials for lunch and dinner (check their website). Medium to expensive depending on the time of the day.

- Ban Thai. Mediaum. Reg. Good thai food (at least to me :). Medium.

- Ill Terrazo. Regular for lunch. Italian. At lunch time it feels expensive but you get a LOT of food. Expensive

- Pho Vy. Fav. Vietnamese. Great pho at a very low price. With 12 dollars you can have a very good bowl of pho. Cheap.

- SenZushi. Fav. Japanese. Probably my most frequented restaurant at dinner time. Unfortunately their restaurant burned down so they moved to Wharf street
  (don't go to Fort St). My Japanese friends approve of its quality. Mediaum.

- Ebizo. Japanese. I think this is a very good japanese restaurant, but my heart is with SenZushi. Medium to expensive.

- Foo Ramen. Ramen. This is a Canadianized take on the Japanese food. It can qualify as fast food. They remain open most of the day. I have been there only once
  but I was good. Cheap. They close at 8. 
  http://www.fooramenbar.ca/


**** Lunch time only

- Relish. Hands down *my favorite restaurant in town*. French with asian influence. If you are into food, do yourself a favour and head there. Extremely good
  value for the food (under $20) but please order a real dish, not a sandwich (they are not as good). Tell them Daniel recommended you to go and that you come
  from far, far away to try their food. Jamie is a master cooking fish. On Saturday he serves (what I call his signature dish) Poached eggs on mackarel. It is
  an _amazing_ dish. His smoked chicken on rice was featured in a Vancouver food magazine as one of the best of the year.  Medium.

- Uchida. It is Japanese food with local accents. Cheap and open until food is gone. One of the hidden jewels of Victoria. Uchida and Relish define what west
  coast food is about. Cheap. https://www.facebook.com/UchidaEatery

- Le Petit Dakar. African (sorry, I can't narrow it any more). This is a place where I would like to eat more frequently. Cheap, but delicious food. Sit outside
  to be smoked by the cars and enjoy the view :). My only problem with this restaurant is that it is not really a restaurant, but more like a take-out food place. Cheap.

- Hernande'z. Reg. Mexican. Good tacos, huaraches and burritos. This is probably the best Mexican food in town. Cheap.

- Pink Bicycle. Burgers. I like their portbello burger. Their salads are very good. Other burgers vary in quality in my opinion, but it is a good burger joint.  Mediaum.

- Hanks Untraditional BBQ. Depending on where you come from, this might be good BBQ or not (Americans abstain, you have much better in your side of the
  world). But that is best we have :(  Cheap to medium.

*** Other suggestions

- Bengal Lounge. If you want a drink in a fancy place, this is it. You can just order a cappuccino and enjoy hacking on one of their lounge chairs (I sometimes
  do :) The buffet in the Bengal is expensive, but it is good. So if you are EXTRA hungry, that is the place to go ;) Expensive.

- Bin 4 Lounge. Burgers. Ok. After 9 their burgers are half price. Medium

*** Beer, wine and Bars

- Sorry, I lack experience in that domain. 

*** Coffee

There are great baristas in town.

- Habit. Two locations. I prefer the one on Pandora for hacking. No internet.
- Macchiato. Fav. Ask for their eponymous drink. My fav. place to hack is counter by their window. No internet.
- Chorizo.
- Cafe Fantastico
- Dolce Vita. Two locations. Anthony is one of the best baristas in town. he is usually in the one on Douglas.

*** Other coffee

- The Bay cafeteria. This is one of the best views of the harbour, if you can sit by the window. The coffee is nothing special, but you get the great view. And
  nobody is rushing you. I know at least one more prof who uses it for quiet work time.
- Murchies. This is the place for desserts (and tea). 

*** Internet

Ever since Shaw started to offer city-wide Internet I stop looking for free wireless networks. Many restaurants offer Shaw or Telus services to subscribers
only. Some locations still offer their own Internet for free. Your safest bet (and good bandwith) is Starbucks and Tim Hortons.

*** Fast food

How fast do you want it? or do you think fast food equals "cheap and pay upfront"? These are based on the latter category.

- Hernande'z. See above. 
- Pig BBQ. Great BBQ sandwiches. Lots of food at a low price. 
- Effes. I really like their chicken shawarma but the place is not as popular as it used to be.
- Fat burger. I only like their vegetarian burger.
- Sally bun (only lunch time). Ok. Seat in the patio at the back. 
- La Cocina De Mama Oli. Try a mexican torta (sandwich). If you want real mexican food, try their Pozole on Sunday.
- Foo Ramen. See above.

* for large groups

What is you are part of a big group? yes, the typical conference connundrum: we need to go out together as a group and find: a) a place that has enough space
for all; b) one that will make almost everybody happy.

My recommendation is head to Trounce Ally and try the Izakaya or the Tapa Bar. Both are decent and have lots of space to accommodate a large group. For more
expensive venus try Zambri's, Ill Terrazo, the Bengal Lounge or Aura. Veneto is another potential option.  The Sticky Wicket is huge so you can probably find
space (but food is terrible).

* Vegans

- Cafe Bliss Weird. If you are vegan, you gotta go there. 
- Lotus pond. Not for me. But vegans love it.

Be love is a new one but I have not been there yet.

* The ones I would like to visit

- Lure
- Jam Caffee
- O'Bistro

* The ones I avoid (which are relatively highly ranked, and I have visited)

In my own experience, these places are not worth it:

- Bard & Banker Public House
- Paggliacci's.
- The Clay Pigeon
- Red Fish/Blue fish. Yes, i listed it above, but I don't like it because I like to have a place to sit when I eat. And their tacos are not great, in my opinion.
- Most restaurants on Wharf (except Sen Zushi)
- Santiago's
- Ca Va
- John's place.
- Nautical Nellies
- Swans Brewpub
- The Noodle Box
- Earls
- Sticky Wicket
- Venus sophia (they kicked me out because I was using a laptop!)
- Cafe Mexico
- Black Olive

* The ones I don't have interest in visiting

- Blue fox Cafe
- Irish times.
- The Old Spaguetti Factory
- Cora.


For any comments, suggestions, complaints, kudos, email me at dmg@uvic.ca


